name: CI

on: 
  push:
    branches: 
      - master

jobs:
  validate-templates:
    runs-on: altemista/dev-portal:latest 
    steps:
      - name: Validate 
        run: for i in templates/* ; do /usr/src/app/server/scripts/parser $i ; done
  update-portal:
    runs-on: ubuntu-latest
    steps:
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
      # TODO: Search for a better way to update all nodes behind load balancer ...
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
