name: Update Portal
on: 
  push:
    branches: 
      - testing
jobs:
  update-portal:
    runs-on: ubuntu-latest
    steps:
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
      # TODO: Search for a better way to update all nodes behind load balancer ...
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
    - name: Call webhook
      run: curl -X POST https://testdev.altemista.cloud/api/webhook
